package com.nammamistri.app.ui

enum class AppLanguage { English, Kannada }

data class T(
    val appName: String,
    val tagline: String,
    val projects: String,
    val workers: String,
    val expenses: String,
    val photos: String,
    val summary: String,
    val addProject: String,
    val projectName: String,
    val totalDays: String,
    val completedDays: String,
    val remainingDays: String,
    val searchProjects: String,
    val edit: String,
    val delete: String,
    val save: String,
    val cancel: String,
    val confirmDelete: String,
    val deleteProjectMessage: String,
    val open: String,
    val noProjects: String,
    val selectProject: String,
    val addWorker: String,
    val workerName: String,
    val wage: String,
    val advance: String,
    val daysWorked: String,
    val updateAttendance: String,
    val noWorkers: String,
    val addExpense: String,
    val expenseTitle: String,
    val amount: String,
    val noExpenses: String,
    val addPhoto: String,
    val pickPhoto: String,
    val photoUri: String,
    val noPhotos: String,
    val totalWorkers: String,
    val labourCost: String,
    val totalExpenses: String,
    val finalTotal: String,
    val createdDate: String,
    val progress: String,
    val updateProgress: String,
    val language: String,
    val english: String,
    val kannada: String
)

object AppText {
    fun of(language: AppLanguage): T = when (language) {
        AppLanguage.English -> T(
            appName = "NammaMistri",
            tagline = "Construction work made simple",
            projects = "Projects",
            workers = "Workers",
            expenses = "Expenses",
            photos = "Photos",
            summary = "Summary",
            addProject = "Add Project",
            projectName = "Project name",
            totalDays = "Total days",
            completedDays = "Completed days",
            remainingDays = "Remaining days",
            searchProjects = "Search projects",
            edit = "Edit",
            delete = "Delete",
            save = "Save",
            cancel = "Cancel",
            confirmDelete = "Delete project?",
            deleteProjectMessage = "This will remove the project with all workers, expenses, photos and attendance.",
            open = "Open",
            noProjects = "No projects yet",
            selectProject = "Select a project first",
            addWorker = "Add Worker",
            workerName = "Worker name",
            wage = "Wage",
            advance = "Advance",
            daysWorked = "Days worked",
            updateAttendance = "Update attendance",
            noWorkers = "No workers yet",
            addExpense = "Add Expense",
            expenseTitle = "Expense title",
            amount = "Amount",
            noExpenses = "No expenses yet",
            addPhoto = "Add Photo",
            pickPhoto = "Pick photo",
            photoUri = "Photo URI",
            noPhotos = "No photos yet",
            totalWorkers = "Total workers",
            labourCost = "Labour cost",
            totalExpenses = "Total expenses",
            finalTotal = "Final total",
            createdDate = "Created date",
            progress = "Progress",
            updateProgress = "Update progress",
            language = "Language",
            english = "English",
            kannada = "Kannada"
        )

        AppLanguage.Kannada -> T(
            appName = "ನಮ್ಮ ಮಿಸ್ತ್ರಿ",
            tagline = "ನಿರ್ಮಾಣ ಕೆಲಸ ಸುಲಭವಾಗಿ",
            projects = "ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು",
            workers = "ಕಾರ್ಮಿಕರು",
            expenses = "ಖರ್ಚುಗಳು",
            photos = "ಫೋಟೋಗಳು",
            summary = "ಸಾರಾಂಶ",
            addProject = "ಪ್ರಾಜೆಕ್ಟ್ ಸೇರಿಸಿ",
            projectName = "ಪ್ರಾಜೆಕ್ಟ್ ಹೆಸರು",
            totalDays = "ಒಟ್ಟು ದಿನಗಳು",
            completedDays = "ಮುಗಿದ ದಿನಗಳು",
            remainingDays = "ಬಾಕಿ ದಿನಗಳು",
            searchProjects = "ಪ್ರಾಜೆಕ್ಟ್ ಹುಡುಕಿ",
            edit = "ತಿದ್ದು",
            delete = "ಅಳಿಸಿ",
            save = "ಉಳಿಸಿ",
            cancel = "ರದ್ದು",
            confirmDelete = "ಪ್ರಾಜೆಕ್ಟ್ ಅಳಿಸಬೇಕೆ?",
            deleteProjectMessage = "ಇದರಿಂದ ಪ್ರಾಜೆಕ್ಟ್ ಜೊತೆಗೆ ಕಾರ್ಮಿಕರು, ಖರ್ಚುಗಳು, ಫೋಟೋಗಳು ಮತ್ತು ಹಾಜರಾತಿ ಅಳಿಸಲಾಗುತ್ತದೆ.",
            open = "ತೆರೆ",
            noProjects = "ಇನ್ನೂ ಪ್ರಾಜೆಕ್ಟ್ ಇಲ್ಲ",
            selectProject = "ಮೊದಲು ಪ್ರಾಜೆಕ್ಟ್ ಆಯ್ಕೆ ಮಾಡಿ",
            addWorker = "ಕಾರ್ಮಿಕ ಸೇರಿಸಿ",
            workerName = "ಕಾರ್ಮಿಕ ಹೆಸರು",
            wage = "ಕೂಲಿ",
            advance = "ಮುಂಗಡ",
            daysWorked = "ಕೆಲಸ ಮಾಡಿದ ದಿನಗಳು",
            updateAttendance = "ಹಾಜರಾತಿ ನವೀಕರಿಸಿ",
            noWorkers = "ಇನ್ನೂ ಕಾರ್ಮಿಕರು ಇಲ್ಲ",
            addExpense = "ಖರ್ಚು ಸೇರಿಸಿ",
            expenseTitle = "ಖರ್ಚಿನ ಹೆಸರು",
            amount = "ಮೊತ್ತ",
            noExpenses = "ಇನ್ನೂ ಖರ್ಚುಗಳು ಇಲ್ಲ",
            addPhoto = "ಫೋಟೋ ಸೇರಿಸಿ",
            pickPhoto = "ಫೋಟೋ ಆಯ್ಕೆ",
            photoUri = "ಫೋಟೋ URI",
            noPhotos = "ಇನ್ನೂ ಫೋಟೋಗಳು ಇಲ್ಲ",
            totalWorkers = "ಒಟ್ಟು ಕಾರ್ಮಿಕರು",
            labourCost = "ಕಾರ್ಮಿಕ ವೆಚ್ಚ",
            totalExpenses = "ಒಟ್ಟು ಖರ್ಚು",
            finalTotal = "ಅಂತಿಮ ಒಟ್ಟು",
            createdDate = "ರಚಿಸಿದ ದಿನಾಂಕ",
            progress = "ಪ್ರಗತಿ",
            updateProgress = "ಪ್ರಗತಿ ನವೀಕರಿಸಿ",
            language = "ಭಾಷೆ",
            english = "English",
            kannada = "ಕನ್ನಡ"
        )
    }
}
